export enum Module {
  DASHBOARD = "DASHBOARD",
  AI_ENGINE = "AI_ENGINE",
  SOCIAL = "SOCIAL",
  MARKETING = "MARKETING",
  NAVIGATION = "NAVIGATION",
  CREATOR = "CREATOR",
  DOCS = "DOCS",
  DEPLOYMENT = "DEPLOYMENT",
  COMMUNICATION = "COMMUNICATION",
  SALES = "SALES",
  SETTINGS = "SETTINGS",
  AR_VIEW = "AR_VIEW",
  ASSISTANT = "ASSISTANT",
  SMART_INBOX = "SMART_INBOX",
  CLOUD_CONFIG = "CLOUD_CONFIG",
  COLLABORATION = "COLLABORATION",
  CONTENT_HUB = "CONTENT_HUB",
  AI_GENERATOR = "AI_GENERATOR",
  DEPENDENCY_MAP = "DEPENDENCY_MAP",
}

export interface NavItem {
  id: Module;
  label: string;
  icon: string;
  description: string;
}
